spring:
    datasource:
        url: jdbc:mysql://localhost:3306/todo_list?createDatabaseIfNotExist=true
        username: springstudent
        password: springstudent
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
